### ISSUE TITLE
Splash screen> remove the 3 dots below

### ISSUE THREAD

**Issue by Anupriyabanger** [Anupriyabanger/my_cloud#1]
Its useless as there is only one screen
![image](https://github.com/Anupriyabanger/my_cloud/assets/109590553/354aacb3-3270-489c-9c5d-1cae5b1cfb6a)

**Comment by Anupriyabanger** [comment]
@Mehulna Here's the content for the other 2 splash screens
1. Empowering Seamless Guest Experiences: Effortlessly manage guest reservations, check-ins, and check-outs. 
2. Elevating Housekeeping Standards: Optimize housekeeping operations with real-time room status updates, cleaning schedules, and efficient task management.

**Comment by Mehulna** [comment]
Done @Anupriyabanger @Ayushvayuz
