### ISSUE TITLE
Search details> Data is missing, check figma

### ISSUE THREAD

**Issue by Anupriyabanger** [Anupriyabanger/my_cloud#127]
![image](https://github.com/Anupriyabanger/my_cloud/assets/109590553/8a1f1eb3-e16b-4219-83b5-4e78328baaac)

**Comment by Ayushvayuz** [comment]
These data are not coming from the api, some card has data which is shown in shared picture.
![Screenshot_2024-05-21-12-20-10-059_com](https://github.com/Anupriyabanger/my_cloud/assets/136789746/02f2729a-8b60-4c93-b907-28ebdc78b533)
